In [1]:
import numpy as np

In [2]:
x=np.array([5,6])

In [3]:
y=np.array([2,3])

In [4]:
np.greater(x,y)

array([ True,  True])

In [5]:
np.greater_equal(x,y)

array([ True,  True])

In [6]:
np.less(x,y)

array([False, False])

In [7]:
np.less_equal(x,y)

array([False, False])

In [8]:
z=np.array([3,6])

In [9]:
np.greater_equal(x,z)

array([ True,  True])

In [10]:
np.greater(x,z)

array([ True, False])