In [1]:
import numpy as np


In [2]:
x=np.array([1,2],[3,4],[5,6])

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [3]:
x=np.array([1,2],[3,4])

TypeError: Field elements must be 2- or 3-tuples, got '3'

In [4]:
x=np.array([[1,2],[3,4]])

In [5]:
print(x)

[[1 2]
 [3 4]]


In [6]:
sum=np.sum(x)



In [7]:
print(sum)

10


In [8]:
np.sum(x,axis=0)#col

array([4, 6])

In [9]:
np.sum(x,axis=1)#row

array([3, 7])