In [1]:
import numpy as np


In [2]:
x=np.arange(5)

In [20]:
y=np.arange(5,10)

In [18]:
print(x)

[0 1 2 3 4]


In [21]:
print(y)

[5 6 7 8 9]


In [22]:
np.equal(x,y)

array([False, False, False, False, False])

In [7]:
z=np.arange(5)

In [10]:
np.equal(x,z)

array([ True,  True,  True,  True,  True])